version: "3"

services:

  server:

    build: WAID-server/
        args:
            MODE: --client
       
    ports:
      - 5000:5000

  client:
    build: WAID-client/
    stdin_open: true

    depends_on:
      - server
      
    ports:
      - 3000:3000

