version: "3.7"

services:

  server:

    build: 
        context: ./WAID-server
        args:
            MODE: --client
        
       
    ports:
      - 5000:5000

  client:
    build: 
        context: ./WAID-client
        args:
          ADDRESS: "${ADDRESS:-localhost}"

          
    stdin_open: true

    depends_on:
      - server
      
    ports:
      - 3000:3000

